server:
  port: 9097

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:mysql://localhost:3306/online_book_store
    username: sipun
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update